# Generated by Django 3.2.4 on 2021-06-11 18:58

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="user",
            name="not_dead_tomorrow",
        ),
        migrations.RemoveConstraint(
            model_name="user",
            name="born_before_today",
        ),
        migrations.AlterField(
            model_name="user",
            name="honorific_prefix",
            field=models.CharField(
                blank=True,
                choices=[
                    (None, "No Selection, Declined To Answer"),
                    ("Mr", "Single or Married Man"),
                    ("Mrs", "Married Woman"),
                    ("Ms", "Single or Married Woman"),
                    ("Dr", "Medical Doctor"),
                    (
                        "Hon",
                        "Honorable (Judge, Justice, other High Ranking Gov official",
                    ),
                    ("Eld", "Elder (religious title)"),
                    ("Fth", "Father (religious title)"),
                    ("Bth", "Brother (religious title)"),
                    ("Sis", "Sister (nun or other female religious leader)"),
                    ("Rev", "Reverand (Religious leader"),
                    ("Rab", "Rabbi (religious leader usually of jewish faith)"),
                ],
                default="No Selection, Declined To Answer",
                max_length=4,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="honorific_suffix",
            field=models.CharField(
                blank=True,
                choices=[
                    (None, "No Selection, Declined To Answer"),
                    ("PhD", "Doctoralily Educated"),
                    ("Esq", "Esquire, Lawyer"),
                ],
                default="No Selection, Declined To Answer",
                max_length=4,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                check=models.Q(("date_of_death__lte", datetime.date(2021, 6, 12))),
                name="not_dead_tomorrow",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                check=models.Q(("date_of_birth__lte", datetime.date(2021, 6, 11))),
                name="born_before_today",
            ),
        ),
    ]
