# Generated by Django 3.2.4 on 2021-06-14 10:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210613_2012'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='not_dead_tomorrow',
        ),
        migrations.RemoveConstraint(
            model_name='user',
            name='born_before_today',
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(check=models.Q(('date_of_death__lte', datetime.date(2021, 6, 15))), name='not_dead_tomorrow'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(check=models.Q(('date_of_birth__lte', datetime.date(2021, 6, 14))), name='born_before_today'),
        ),
    ]
