# Generated by Django 3.2.3 on 2021-05-30 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_profile_addresses"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="street2",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
