# Generated by Django 3.2.3 on 2021-06-01 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_address_street2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                default="default.webp", upload_to="raw_profile_pictures"
            ),
        ),
    ]
