# Generated by Django 3.2.3 on 2021-06-03 01:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210603_0056'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='age_gte_18',
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(check=models.Q(('date_of_death__lt', datetime.datetime(2021, 6, 4, 1, 18, 56, 404490))), name='not_dead_tomorrow'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(check=models.Q(('date_of_birth__lte', datetime.datetime(2021, 6, 3, 1, 18, 56, 404527))), name='born_before_today'),
        ),
    ]
