# Generated by Django 3.2.3 on 2021-06-03 14:37

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_auto_20210603_0118"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="user",
            name="not_dead_tomorrow",
        ),
        migrations.RemoveConstraint(
            model_name="user",
            name="born_before_today",
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                check=models.Q(
                    (
                        "date_of_death__lte",
                        datetime.datetime(2021, 6, 4, 14, 37, 52, 678995),
                    )
                ),
                name="not_dead_tomorrow",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                check=models.Q(
                    (
                        "date_of_birth__lte",
                        datetime.datetime(2021, 6, 3, 14, 37, 52, 679012),
                    )
                ),
                name="born_before_today",
            ),
        ),
    ]
