# Generated by Django 3.2.4 on 2021-06-04 14:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20210604_1452'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='not_dead_tomorrow',
        ),
        migrations.RemoveConstraint(
            model_name='user',
            name='born_before_today',
        ),
        migrations.AddField(
            model_name='user',
            name='retention_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(check=models.Q(('date_of_death__lte', datetime.datetime(2021, 6, 5, 14, 58, 10, 515085))), name='not_dead_tomorrow'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(check=models.Q(('date_of_birth__lte', datetime.datetime(2021, 6, 4, 14, 58, 10, 515102))), name='born_before_today'),
        ),
    ]
