# Generated by Django 3.2.3 on 2021-06-05 14:01

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0019_auto_20210604_1458"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="user",
            name="not_dead_tomorrow",
        ),
        migrations.RemoveConstraint(
            model_name="user",
            name="born_before_today",
        ),
        migrations.AddField(
            model_name="profile",
            name="mobile_number",
            field=models.CharField(
                blank=True,
                help_text="Numbers only no spaces or characters. Example: xxxxxxxxxx",
                max_length=15,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                check=models.Q(
                    (
                        "date_of_death__lte",
                        datetime.datetime(2021, 6, 6, 14, 1, 43, 315390),
                    )
                ),
                name="not_dead_tomorrow",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                check=models.Q(
                    (
                        "date_of_birth__lte",
                        datetime.datetime(2021, 6, 5, 14, 1, 43, 315421),
                    )
                ),
                name="born_before_today",
            ),
        ),
    ]
