# Generated by Django 3.2.4 on 2021-06-05 15:29

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0023_auto_20210605_1524"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="user",
            name="not_dead_tomorrow",
        ),
        migrations.RemoveConstraint(
            model_name="user",
            name="born_before_today",
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                check=models.Q(
                    (
                        "date_of_death__lte",
                        datetime.datetime(2021, 6, 6, 15, 29, 23, 288477),
                    )
                ),
                name="not_dead_tomorrow",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                check=models.Q(
                    (
                        "date_of_birth__lte",
                        datetime.datetime(2021, 6, 5, 15, 29, 23, 288493),
                    )
                ),
                name="born_before_today",
            ),
        ),
    ]
