# Generated by Django 3.2.4 on 2021-06-06 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0026_user_nickname"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="madien_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
