# Generated by Django 3.2.3 on 2021-06-07 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0025_auto_20210606_0112"),
        ("users", "0027_user_madien_name"),
    ]

    operations = []
