# Generated by Django 3.2.4 on 2021-06-06 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            (None, "No Selection, Declined To Answer"),
                            (
                                "M",
                                "I identify as a male or a man (i.e. male, cis-gender male), and prefer to be called sir",
                            ),
                            (
                                "F",
                                "I identify as a female or a woman (i.e. female, cis-gender female),  and prefer to be called ma'am.",
                            ),
                            (
                                "MTF",
                                "Assigned male at birth, but currently identify as female.",
                            ),
                            (
                                "FTM",
                                "Assigned female at birth but currently identify as male.",
                            ),
                            ("NBN", "Neither male nor female, somewhere in between."),
                        ],
                        default="No Selection, Declined To Answer",
                        max_length=3,
                    ),
                ),
                (
                    "ethnicity",
                    models.CharField(
                        choices=[
                            (None, "No Selection, Declined To Answer"),
                            (
                                "ASN",
                                "Asian - Far East, Southeast Asia, or the Indian subcontinent including, for example, Cambodia, China, India, Japan, Korea, Malaysia, Pakistan, the Philippine Islands, Thailand, and Vietnam.",
                            ),
                            (
                                "BLK",
                                "Black - origins in any of the Black racial groups of Africa including Carribean Islands.",
                            ),
                            ("NAT", "Native American or Alaskan Native."),
                            (
                                "HPN",
                                "Hispanic - Centeral and South America, Carribbean Islands.",
                            ),
                            (
                                "MDE",
                                "Middle Eastern - the Middle East, or North Africa.",
                            ),
                            (
                                "HWN",
                                "Native Hawaii, Guam, Samoa, or other Pacific Islands.",
                            ),
                            ("OTH", "Other/Multiple"),
                            ("WHT", "White-origins in Europe."),
                        ],
                        default="No Selection, Declined To Answer",
                        max_length=3,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sponsor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guarantor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appointments.patient",
                    ),
                ),
                (
                    "scheduler",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
