# Generated by Django 3.2.4 on 2021-06-08 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="action_status",
            field=models.CharField(
                choices=[
                    (None, "('UNKNOWN')"),
                    ("CMPL", "Completed"),
                    ("CAND", "Canelled"),
                    ("SCHD", "Scheduled"),
                    ("INPR", "In Progress"),
                ],
                default="('UNKNOWN')",
                max_length=4,
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="end_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="location",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="scheduled_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="start_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
