# Generated by Django 3.2.4 on 2021-06-17 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0003_auto_20210615_2032"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="is_archived",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
