# Generated by Django 3.2.4 on 2021-06-13 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0004_auto_20210608_2029"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="date_modified",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="scheduled_time",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
