# Generated by Django 3.2.4 on 2021-06-18 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0004_appointment_is_archived"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="date_archived",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
