# Generated by Django 3.2.4 on 2021-06-13 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0005_auto_20210613_2012"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="date_modified",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
