# Generated by Django 3.2.4 on 2021-06-14 11:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_alter_appointment_date_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='visit_identifier',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
