# Generated by Django 3.2.4 on 2021-06-14 19:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_appointment_visit_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='visit_identifier',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
